### ISSUE TITLE
issue with customUI directory not getting unzipped correctly

### ISSUE THREAD

**Issue by ppolito** [AppXpress/PlatformModuleBuilder#11]
I have a zipped file from production for a platform module - when I used pmextractor against it, it did not seem to extract my directory /customUI/Archive_v003.zip to anywhere.  Did the zip file need to be named a specific way for this to have worked?

**Comment by jjdonov** [comment]
Hi @ppolito, have you tried using the `--overwriteFef` option?

That should solve your problem. 

Did the platfrom module you are exracting already exist in the localDir? It seems that logic to check this needs to be created.

**Comment by ppolito** [comment]
yes - with the option works well.

Thanks...
Paula
