### ISSUE TITLE
add argument for easier .zip picking

### ISSUE THREAD

**Issue by jfern108** [AppXpress/PlatformModuleBuilder#6]
currently the user has to copy or type in the entire .zip file name (which can lead to manual errors).  add an argument that instead of asking for the .zip, provides a numbered list to the user of all .zips in the folder, and allows them to simply select the number for it

example

$pmextractor -l
which .zip would you like to use?
1 - a.zip
2 - b.zip
3 - c.zip
user input: 2

**Comment by jjdonov** [comment]
Closing this enhancement with SHA: 575b7cf0aab43a3ffaf80159011130571a871806
