### ISSUE TITLE
add argument for easier pm folder picking

### ISSUE THREAD

**Issue by jfern108** [AppXpress/PlatformModuleBuilder#8]
when using pmbuilder, you have to type out the full name of the platform module folder.

add an argument that provides a list of all folders int he current folder and lets the user pick based on a numbered list, and not having to type everything out

**Comment by jjdonov** [comment]
Closing this with SHA: fa5202f77134d7ab58c1b30cb77838e6b618de11

PMBuilder can now select modules from customer repo
